ALTER SESSION SET "_ORACLE_SCRIPT"=true; 

CREATE USER DASQL IDENTIFIED BY 1234;
ALTER USER DASQL ACCOUNT UNLOCK;
GRANT RESOURCE, DBA, CONNECT TO DASQL;

CREATE TABLESPACE DASQL_DATA
datafile 'C:\app\leeko\product\18.0.0\oradata\XE\DASQL_DATA.dbf' SIZE 2G
AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TEMPORARY TABLESPACE DASQL_TEMP
TEMPFILE 'C:\app\leeko\product\18.0.0\oradata\XE\DASQL_TEMP.dbf' SIZE 500M
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
;

ALTER USER DASQL DEFAULT TABLESPACE DASQL_DATA;
ALTER USER DASQL TEMPORARY TABLESPACE DASQL_TEMP;
