CREATE TABLE TB_PBTRNSP_DATA
(
  DE VARCHAR2(400) NOT NULL
, HO_LN VARCHAR2(400) NOT NULL
, STATN_NO VARCHAR2(400) NOT NULL
, STATN_NM VARCHAR2(4000)
, FROM_04_HOUR_TO_05_HOUR_TK VARCHAR2(4000)
, FROM_04_HOUR_TO_05_HOUR_GFF VARCHAR2(4000)
, FROM_05_HOUR_TO_06_HOUR_TK VARCHAR2(4000)
, FROM_05_HOUR_TO_06_HOUR_GFF VARCHAR2(4000)
, FROM_06_HOUR_TO_07_HOUR_TK VARCHAR2(4000)
, FROM_06_HOUR_TO_07_HOUR_GFF VARCHAR2(4000)
, FROM_07_HOUR_TO_08_HOUR_TK VARCHAR2(4000)
, FROM_07_HOUR_TO_08_HOUR_GFF VARCHAR2(4000)
, FROM_08_HOUR_TO_09_HOUR_TK VARCHAR2(4000)
, FROM_08_HOUR_TO_09_HOUR_GFF VARCHAR2(4000)
, FROM_09_HOUR_TO_10_HOUR_TK VARCHAR2(4000)
, FROM_09_HOUR_TO_10_HOUR_GFF VARCHAR2(4000)
, FROM_10_HOUR_TO_11_HOUR_TK VARCHAR2(4000)
, FROM_10_HOUR_TO_11_HOUR_GFF VARCHAR2(4000)
, FROM_11_HOUR_TO_12_HOUR_TK VARCHAR2(4000)
, FROM_11_HOUR_TO_12_HOUR_GFF VARCHAR2(4000)
, FROM_12_HOUR_TO_13_HOUR_TK VARCHAR2(4000)
, FROM_12_HOUR_TO_13_HOUR_GFF VARCHAR2(4000)
, FROM_13_HOUR_TO_14_HOUR_TK VARCHAR2(4000)
, FROM_13_HOUR_TO_14_HOUR_GFF VARCHAR2(4000)
, FROM_14_HOUR_TO_15_HOUR_TK VARCHAR2(4000)
, FROM_14_HOUR_TO_15_HOUR_GFF VARCHAR2(4000)
, FROM_15_HOUR_TO_16_HOUR_TK VARCHAR2(4000)
, FROM_15_HOUR_TO_16_HOUR_GFF VARCHAR2(4000)
, FROM_16_HOUR_TO_17_HOUR_TK VARCHAR2(4000)
, FROM_16_HOUR_TO_17_HOUR_GFF VARCHAR2(4000)
, FROM_17_HOUR_TO_18_HOUR_TK VARCHAR2(4000)
, FROM_17_HOUR_TO_18_HOUR_GFF VARCHAR2(4000)
, FROM_18_HOUR_TO_19_HOUR_TK VARCHAR2(4000)
, FROM_18_HOUR_TO_19_HOUR_GFF VARCHAR2(4000)
, FROM_19_HOUR_TO_20_HOUR_TK VARCHAR2(4000)
, FROM_19_HOUR_TO_20_HOUR_GFF VARCHAR2(4000)
, FROM_20_HOUR_TO_21_HOUR_TK VARCHAR2(4000)
, FROM_20_HOUR_TO_21_HOUR_GFF VARCHAR2(4000)
, FROM_21_HOUR_TO_22_HOUR_TK VARCHAR2(4000)
, FROM_21_HOUR_TO_22_HOUR_GFF VARCHAR2(4000)
, FROM_22_HOUR_TO_23_HOUR_TK VARCHAR2(4000)
, FROM_22_HOUR_TO_23_HOUR_GFF VARCHAR2(4000)
, FROM_23_HOUR_TO_24_HOUR_TK VARCHAR2(4000)
, FROM_23_HOUR_TO_24_HOUR_GFF VARCHAR2(4000)
, FROM_24_HOUR_TO_01_HOUR_TK VARCHAR2(4000)
, FROM_24_HOUR_TO_01_HOUR_GFF VARCHAR2(4000)
, FROM_01_HOUR_TO_02_HOUR_TK VARCHAR2(4000)
, FROM_01_HOUR_TO_02_HOUR_GFF VARCHAR2(4000)
, FROM_02_HOUR_TO_03_HOUR_TK VARCHAR2(4000)
, FROM_02_HOUR_TO_03_HOUR_GFF VARCHAR2(4000)
, FROM_03_HOUR_TO_04_HOUR_TK VARCHAR2(4000)
, FROM_03_HOUR_TO_04_HOUR_GFF VARCHAR2(4000)
, WORK_DT VARCHAR2(4000)      
);

SELECT COUNT(*) FROM TB_PBTRNSP_DATA; 

CREATE TABLE TB_PBTRNSP
(
  STATN_NO NUMBER(10) NOT NULL
, STATN_NM VARCHAR2(50)
, HO_LN VARCHAR2(50)
, STD_MT CHAR(6) NOT NULL
, BEGIN_TIME CHAR(4) NOT NULL
, END_TIME CHAR(4) NOT NULL
, TKCAR_GFF_SE_CD CHAR(2) NOT NULL --'TK':승차, 'GF':하차
, NMPR_CNT NUMBER(15) --인원수
, CONSTRAINT TB_PBTRNSP_PK PRIMARY KEY (STATN_NO, STD_MT, BEGIN_TIME, END_TIME, TKCAR_GFF_SE_CD)
);


INSERT INTO TB_PBTRNSP
SELECT A.STATN_NO, A.STATN_NM, A.HO_LN, '202010' AS STD_MT
     , CASE WHEN A.LVL = 1  THEN '0400' WHEN A.LVL = 2  THEN '0400' WHEN A.LVL = 3  THEN '0500' WHEN A.LVL = 4  THEN '0500' WHEN A.LVL = 5  THEN '0600' WHEN A.LVL = 6  THEN '0600'
            WHEN A.LVL = 7  THEN '0700' WHEN A.LVL = 8  THEN '0700' WHEN A.LVL = 9  THEN '0800' WHEN A.LVL = 10 THEN '0800' WHEN A.LVL = 11 THEN '0900' WHEN A.LVL = 12 THEN '0900'
            WHEN A.LVL = 13 THEN '1000' WHEN A.LVL = 14 THEN '1000' WHEN A.LVL = 15 THEN '1100' WHEN A.LVL = 16 THEN '1100' WHEN A.LVL = 17 THEN '1200' WHEN A.LVL = 18 THEN '1200'
            WHEN A.LVL = 19 THEN '1300' WHEN A.LVL = 20 THEN '1300' WHEN A.LVL = 21 THEN '1400' WHEN A.LVL = 22 THEN '1400' WHEN A.LVL = 23 THEN '1500' WHEN A.LVL = 24 THEN '1500'
            WHEN A.LVL = 25 THEN '1600' WHEN A.LVL = 26 THEN '1600' WHEN A.LVL = 27 THEN '1700' WHEN A.LVL = 28 THEN '1700' WHEN A.LVL = 29 THEN '1800' WHEN A.LVL = 30 THEN '1800'
            WHEN A.LVL = 31 THEN '1900' WHEN A.LVL = 32 THEN '1900' WHEN A.LVL = 33 THEN '2000' WHEN A.LVL = 34 THEN '2000' WHEN A.LVL = 35 THEN '2100' WHEN A.LVL = 36 THEN '2100'
            WHEN A.LVL = 37 THEN '2200' WHEN A.LVL = 38 THEN '2200' WHEN A.LVL = 39 THEN '2300' WHEN A.LVL = 40 THEN '2300' WHEN A.LVL = 41 THEN '2400' WHEN A.LVL = 42 THEN '2400'
            WHEN A.LVL = 43 THEN '0100' WHEN A.LVL = 44 THEN '0100' WHEN A.LVL = 45 THEN '0200' WHEN A.LVL = 46 THEN '0200' WHEN A.LVL = 47 THEN '0300' WHEN A.LVL = 48 THEN '0300'
            ELSE '' END AS BEGIN_TIME
     , CASE WHEN A.LVL = 1  THEN '0500' WHEN A.LVL = 2  THEN '0500' WHEN A.LVL = 3  THEN '0600' WHEN A.LVL = 4  THEN '0600' WHEN A.LVL = 5  THEN '0700' WHEN A.LVL = 6  THEN '0700'
            WHEN A.LVL = 7  THEN '0800' WHEN A.LVL = 8  THEN '0800' WHEN A.LVL = 9  THEN '0900' WHEN A.LVL = 10 THEN '0900' WHEN A.LVL = 11 THEN '1000' WHEN A.LVL = 12 THEN '1000'
            WHEN A.LVL = 13 THEN '1100' WHEN A.LVL = 14 THEN '1100' WHEN A.LVL = 15 THEN '1200' WHEN A.LVL = 16 THEN '1200' WHEN A.LVL = 17 THEN '1300' WHEN A.LVL = 18 THEN '1300'
            WHEN A.LVL = 19 THEN '1400' WHEN A.LVL = 20 THEN '1400' WHEN A.LVL = 21 THEN '1500' WHEN A.LVL = 22 THEN '1500' WHEN A.LVL = 23 THEN '1600' WHEN A.LVL = 24 THEN '1600'
            WHEN A.LVL = 25 THEN '1700' WHEN A.LVL = 26 THEN '1700' WHEN A.LVL = 27 THEN '1800' WHEN A.LVL = 28 THEN '1800' WHEN A.LVL = 29 THEN '1900' WHEN A.LVL = 30 THEN '1900'
            WHEN A.LVL = 31 THEN '2000' WHEN A.LVL = 32 THEN '2000' WHEN A.LVL = 33 THEN '2100' WHEN A.LVL = 34 THEN '2100' WHEN A.LVL = 35 THEN '2200' WHEN A.LVL = 36 THEN '2200'
            WHEN A.LVL = 37 THEN '2300' WHEN A.LVL = 38 THEN '2300' WHEN A.LVL = 39 THEN '2400' WHEN A.LVL = 40 THEN '2400' WHEN A.LVL = 41 THEN '0100' WHEN A.LVL = 42 THEN '0100'
            WHEN A.LVL = 43 THEN '0200' WHEN A.LVL = 44 THEN '0200' WHEN A.LVL = 45 THEN '0300' WHEN A.LVL = 46 THEN '0300' WHEN A.LVL = 47 THEN '0400' WHEN A.LVL = 48 THEN '0400'
            ELSE '' END AS END_TIME
     , CASE WHEN MOD(A.LVL, 2) = 1 THEN 'TK'  
            WHEN MOD(A.LVL, 2) = 0 THEN 'GF'  
            ELSE '' END AS TKCAR_GFF_SE_CD
     , CASE WHEN A.LVL = 1  THEN TO_NUMBER(REPLACE(FROM_04_HOUR_TO_05_HOUR_TK, ',','')) WHEN A.LVL = 2  THEN TO_NUMBER(REPLACE(FROM_04_HOUR_TO_05_HOUR_GFF, ',','')) 
            WHEN A.LVL = 3  THEN TO_NUMBER(REPLACE(FROM_05_HOUR_TO_06_HOUR_TK, ',','')) WHEN A.LVL = 4  THEN TO_NUMBER(REPLACE(FROM_05_HOUR_TO_06_HOUR_GFF, ',','')) 
            WHEN A.LVL = 5  THEN TO_NUMBER(REPLACE(FROM_06_HOUR_TO_07_HOUR_TK, ',','')) WHEN A.LVL = 6  THEN TO_NUMBER(REPLACE(FROM_06_HOUR_TO_07_HOUR_GFF, ',','')) 
            WHEN A.LVL = 7  THEN TO_NUMBER(REPLACE(FROM_07_HOUR_TO_08_HOUR_TK, ',','')) WHEN A.LVL = 8  THEN TO_NUMBER(REPLACE(FROM_07_HOUR_TO_08_HOUR_GFF, ',','')) 
            WHEN A.LVL = 9  THEN TO_NUMBER(REPLACE(FROM_08_HOUR_TO_09_HOUR_TK, ',','')) WHEN A.LVL = 10 THEN TO_NUMBER(REPLACE(FROM_08_HOUR_TO_09_HOUR_GFF, ',','')) 
            WHEN A.LVL = 11 THEN TO_NUMBER(REPLACE(FROM_09_HOUR_TO_10_HOUR_TK, ',','')) WHEN A.LVL = 12 THEN TO_NUMBER(REPLACE(FROM_09_HOUR_TO_10_HOUR_GFF, ',','')) 
            WHEN A.LVL = 13 THEN TO_NUMBER(REPLACE(FROM_10_HOUR_TO_11_HOUR_TK, ',','')) WHEN A.LVL = 14 THEN TO_NUMBER(REPLACE(FROM_10_HOUR_TO_11_HOUR_GFF, ',','')) 
            WHEN A.LVL = 15 THEN TO_NUMBER(REPLACE(FROM_11_HOUR_TO_12_HOUR_TK, ',','')) WHEN A.LVL = 16 THEN TO_NUMBER(REPLACE(FROM_11_HOUR_TO_12_HOUR_GFF, ',','')) 
            WHEN A.LVL = 17 THEN TO_NUMBER(REPLACE(FROM_12_HOUR_TO_13_HOUR_TK, ',','')) WHEN A.LVL = 18 THEN TO_NUMBER(REPLACE(FROM_12_HOUR_TO_13_HOUR_GFF, ',','')) 
            WHEN A.LVL = 19 THEN TO_NUMBER(REPLACE(FROM_13_HOUR_TO_14_HOUR_TK, ',','')) WHEN A.LVL = 20 THEN TO_NUMBER(REPLACE(FROM_13_HOUR_TO_14_HOUR_GFF, ',','')) 
            WHEN A.LVL = 21 THEN TO_NUMBER(REPLACE(FROM_14_HOUR_TO_15_HOUR_TK, ',','')) WHEN A.LVL = 22 THEN TO_NUMBER(REPLACE(FROM_14_HOUR_TO_15_HOUR_GFF, ',','')) 
            WHEN A.LVL = 23 THEN TO_NUMBER(REPLACE(FROM_15_HOUR_TO_16_HOUR_TK, ',','')) WHEN A.LVL = 24 THEN TO_NUMBER(REPLACE(FROM_15_HOUR_TO_16_HOUR_GFF, ',','')) 
            WHEN A.LVL = 25 THEN TO_NUMBER(REPLACE(FROM_16_HOUR_TO_17_HOUR_TK, ',','')) WHEN A.LVL = 26 THEN TO_NUMBER(REPLACE(FROM_16_HOUR_TO_17_HOUR_GFF, ',','')) 
            WHEN A.LVL = 27 THEN TO_NUMBER(REPLACE(FROM_17_HOUR_TO_18_HOUR_TK, ',','')) WHEN A.LVL = 28 THEN TO_NUMBER(REPLACE(FROM_17_HOUR_TO_18_HOUR_GFF, ',','')) 
            WHEN A.LVL = 29 THEN TO_NUMBER(REPLACE(FROM_18_HOUR_TO_19_HOUR_TK, ',','')) WHEN A.LVL = 30 THEN TO_NUMBER(REPLACE(FROM_18_HOUR_TO_19_HOUR_GFF, ',','')) 
            WHEN A.LVL = 31 THEN TO_NUMBER(REPLACE(FROM_19_HOUR_TO_20_HOUR_TK, ',','')) WHEN A.LVL = 32 THEN TO_NUMBER(REPLACE(FROM_19_HOUR_TO_20_HOUR_GFF, ',','')) 
            WHEN A.LVL = 33 THEN TO_NUMBER(REPLACE(FROM_20_HOUR_TO_21_HOUR_TK, ',','')) WHEN A.LVL = 34 THEN TO_NUMBER(REPLACE(FROM_20_HOUR_TO_21_HOUR_GFF, ',','')) 
            WHEN A.LVL = 35 THEN TO_NUMBER(REPLACE(FROM_21_HOUR_TO_22_HOUR_TK, ',','')) WHEN A.LVL = 36 THEN TO_NUMBER(REPLACE(FROM_21_HOUR_TO_22_HOUR_GFF, ',','')) 
            WHEN A.LVL = 37 THEN TO_NUMBER(REPLACE(FROM_22_HOUR_TO_23_HOUR_TK, ',','')) WHEN A.LVL = 38 THEN TO_NUMBER(REPLACE(FROM_22_HOUR_TO_23_HOUR_GFF, ',','')) 
            WHEN A.LVL = 39 THEN TO_NUMBER(REPLACE(FROM_23_HOUR_TO_24_HOUR_TK, ',','')) WHEN A.LVL = 40 THEN TO_NUMBER(REPLACE(FROM_23_HOUR_TO_24_HOUR_GFF, ',','')) 
            WHEN A.LVL = 41 THEN TO_NUMBER(REPLACE(FROM_24_HOUR_TO_01_HOUR_TK, ',','')) WHEN A.LVL = 42 THEN TO_NUMBER(REPLACE(FROM_24_HOUR_TO_01_HOUR_GFF, ',','')) 
            WHEN A.LVL = 43 THEN TO_NUMBER(REPLACE(FROM_01_HOUR_TO_02_HOUR_TK, ',','')) WHEN A.LVL = 44 THEN TO_NUMBER(REPLACE(FROM_01_HOUR_TO_02_HOUR_GFF, ',','')) 
            WHEN A.LVL = 45 THEN TO_NUMBER(REPLACE(FROM_02_HOUR_TO_03_HOUR_TK, ',','')) WHEN A.LVL = 46 THEN TO_NUMBER(REPLACE(FROM_02_HOUR_TO_03_HOUR_GFF, ',','')) 
            WHEN A.LVL = 47 THEN TO_NUMBER(REPLACE(FROM_03_HOUR_TO_04_HOUR_TK, ',','')) WHEN A.LVL = 48 THEN TO_NUMBER(REPLACE(FROM_03_HOUR_TO_04_HOUR_GFF, ',','')) 
            ELSE 0 END AS NMPR_CO
  FROM 
     (
       SELECT A.*, B.*
         FROM TB_PBTRNSP_DATA A
            , (SELECT LEVEL LVL FROM DUAL CONNECT BY LEVEL <= 48) B
     ) A
ORDER BY TO_NUMBER(STATN_NO), BEGIN_TIME, END_TIME;

COMMIT; 


SELECT A.STATN_NO
     , A.STATN_NM
     , A.HO_LN
     , TKCAR_GFF_SE_CD
     , SUM(A.NMPR_CNT) AS NMPR_CNT
  FROM TB_PBTRNSP A
 WHERE A.STD_MT = '202010'
 GROUP BY A.STATN_NO, A.STATN_NM, A.HO_LN, A.TKCAR_GFF_SE_CD
 ORDER BY NMPR_CNT DESC;


SELECT * 
  FROM 
(
SELECT A.STATN_NO, A.STATN_NM, A.HO_LN 
     , A.TK_NMPR_CNT, A.GF_NMPR_CNT
     , ROW_NUMBER() OVER(ORDER BY A.TK_NMPR_CNT) RN_TK_NMPR_CNT_ASC
     , ROW_NUMBER() OVER(ORDER BY A.TK_NMPR_CNT DESC) RN_TK_NMPR_CNT_DESC
     , ROW_NUMBER() OVER(ORDER BY A.GF_NMPR_CNT) RN_GF_NMPR_CNT_ASC
     , ROW_NUMBER() OVER(ORDER BY A.GF_NMPR_CNT DESC) RN_GF_NMPR_CNT_DESC
  FROM 
      (             
            SELECT A.STATN_NO, A.STATN_NM, A.HO_LN
                 , MAX(A.TK_NMPR_CNT) TK_NMPR_CNT
                 , MAX(A.GF_NMPR_CNT) GF_NMPR_CNT
            FROM 
               (
                SELECT 
                       A.STATN_NO, A.STATN_NM, A.HO_LN
                     , CASE WHEN A.TKCAR_GFF_SE_CD = 'TK' THEN NMPR_CNT ELSE 0 END AS TK_NMPR_CNT
                     , CASE WHEN A.TKCAR_GFF_SE_CD = 'GF' THEN NMPR_CNT ELSE 0 END AS GF_NMPR_CNT
                  FROM 
                     (
                        SELECT A.STATN_NO, A.STATN_NM, A.HO_LN, A.TKCAR_GFF_SE_CD
                             , SUM(A.NMPR_CNT) AS NMPR_CNT
                          FROM TB_PBTRNSP A
                         WHERE A.STD_MT = '202010'
                         GROUP BY A.STATN_NO, A.STATN_NM, A.HO_LN, A.TKCAR_GFF_SE_CD
                         ORDER BY NMPR_CNT DESC
                     ) A
                ) A 
            GROUP BY A.STATN_NO, A.STATN_NM, A.HO_LN
     ) A
) 
WHERE RN_TK_NMPR_CNT_ASC = 1 OR RN_TK_NMPR_CNT_DESC = 1  OR RN_GF_NMPR_CNT_ASC = 1  OR RN_GF_NMPR_CNT_DESC = 1  ;



SELECT 
       A.STATN_NO
     , A.STATN_NM
     , A.HO_LN
     , A.NMPR_CNT  
  FROM 
     (
        SELECT A.STATN_NO
             , A.STATN_NM
             , A.HO_LN
             , SUM(A.NMPR_CNT) AS NMPR_CNT 
          FROM TB_PBTRNSP A
          WHERE A.STD_MT = '202010'
            AND A.BEGIN_TIME = '0800'
            AND A.END_TIME = '0900'
            AND A.TKCAR_GFF_SE_CD = 'GF'
         GROUP BY A.STATN_NO, A.STATN_NM, A.HO_LN
         ORDER BY NMPR_CNT DESC
     ) A 
 WHERE ROWNUM <= 10;



SELECT 
       A.STATN_NO
     , A.STATN_NM
     , A.HO_LN
     , A.NMPR_CNT  
  FROM 
     (
        SELECT A.STATN_NO
             , A.STATN_NM
             , A.HO_LN
             , SUM(A.NMPR_CNT) AS NMPR_CNT 
          FROM TB_PBTRNSP A
          WHERE A.STD_MT = '202010'
            AND A.BEGIN_TIME = '1800'
            AND A.END_TIME = '1900'
            AND A.TKCAR_GFF_SE_CD = 'GF'
         GROUP BY A.STATN_NO, A.STATN_NM, A.HO_LN
         ORDER BY NMPR_CNT DESC
     ) A 
 WHERE ROWNUM <= 10;


SELECT 
       A.STATN_NO
     , A.STATN_NM
     , A.HO_LN
     , A.NMPR_CNT  
  FROM 
     (
        SELECT A.STATN_NO
             , A.STATN_NM
             , A.HO_LN
             , SUM(A.NMPR_CNT) AS NMPR_CNT 
          FROM TB_PBTRNSP A
          WHERE A.STD_MT = '202010'
            AND (A.BEGIN_TIME, A.END_TIME) IN ( ('2300', '2400'), ('0000', '0100'), ('0100', '0200'), ('0200', '0300'), ('0300', '0400'))             
            AND A.TKCAR_GFF_SE_CD = 'TK'
         GROUP BY A.STATN_NO, A.STATN_NM, A.HO_LN
         ORDER BY NMPR_CNT DESC
     ) A 
 WHERE ROWNUM <= 10;


SELECT * 
  FROM 
     (
SELECT   
         A.STATN_NO
 , A.STATN_NM
 , A.HO_LN 
 , A.NMPR_CNT
 , ROW_NUMBER() OVER(PARTITION BY A.HO_LN ORDER BY A.NMPR_CNT DESC) AS RN_HO_LN_NMPR_CNT
  FROM 
     (
SELECT
       A.STATN_NO
     , A.STATN_NM
     , A.HO_LN
     , SUM(A.NMPR_CNT) AS NMPR_CNT
  FROM TB_PBTRNSP A
 WHERE A.STD_MT = '202010'
 GROUP BY A.STATN_NO, A.STATN_NM, A.HO_LN
 ORDER BY NMPR_CNT DESC
     ) A 
     ) A      
WHERE RN_HO_LN_NMPR_CNT = 1
ORDER BY NMPR_CNT DESC
;


